# Generated by Django 6.0.5 on 2026-05-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tranche",
                    models.CharField(
                        choices=[
                            ("tranche1", "Tranche 1"),
                            ("tranche2", "Tranche 2"),
                            ("tranche3", "Tranche 3"),
                            ("totalite", "Totalité"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("montant_paye", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "moyen_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("orange_money", "Orange Money"),
                            ("virement", "Virement bancaire"),
                        ],
                        default="especes",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_jour", "À jour"),
                            ("retard", "En retard"),
                            ("solde", "Soldé"),
                        ],
                        default="a_jour",
                        max_length=20,
                    ),
                ),
                ("date_paiement", models.DateTimeField(auto_now_add=True)),
                ("date_echeance", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="inscriptions.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date_paiement"],
            },
        ),
    ]
