# Generated by Django 6.0.5 on 2026-05-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_recu",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "fichier_pdf",
                    models.FileField(blank=True, null=True, upload_to="recus/"),
                ),
                ("envoye_email", models.BooleanField(default=False)),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                (
                    "paiement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recu",
                        to="paiements.paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reçu",
                "verbose_name_plural": "Reçus",
                "ordering": ["-date_generation"],
            },
        ),
    ]
