# Generated by Django 6.0.5 on 2026-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                ("nationalite", models.CharField(default="Guinéenne", max_length=50)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("adresse", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("matricule", models.CharField(blank=True, max_length=20, unique=True)),
                ("filiere", models.CharField(max_length=100)),
                ("niveau", models.CharField(max_length=20)),
                ("annee_academique", models.CharField(max_length=9)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("preinscrit", "Préinscrit"),
                            ("inscrit", "Inscrit"),
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                        ],
                        default="preinscrit",
                        max_length=20,
                    ),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Étudiant",
                "verbose_name_plural": "Étudiants",
                "ordering": ["-date_inscription"],
            },
        ),
    ]
