# Generated by Django 6.0.5 on 2026-05-20 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("identite", "Pièce d'identité"),
                            ("diplome", "Diplôme"),
                            ("photo", "Photo"),
                            ("certificat", "Certificat"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nom_fichier", models.CharField(max_length=200)),
                ("fichier", models.FileField(upload_to="documents/")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="inscriptions.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-date_upload"],
            },
        ),
    ]
