# Generated by Django 6.0.5 on 2026-07-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0001_initial"),
        ("inscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="etudiants",
            field=models.ManyToManyField(
                blank=True, related_name="cours", to="inscriptions.etudiant"
            ),
        ),
    ]
