# Generated by Django 6.0.5 on 2026-09-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0002_cours_etudiants"),
        ("professeurs", "0002_professeur_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="annee_academique",
            field=models.CharField(default="2025-2026", max_length=9),
        ),
        migrations.AddField(
            model_name="cours",
            name="coefficient",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="cours",
            name="credits",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="cours",
            name="filiere",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="cours",
            name="niveau",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="cours",
            name="professeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cours",
                to="professeurs.professeur",
            ),
        ),
    ]
