# Generated by Django 6.0.5 on 2026-07-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(max_length=100)),
                ("nationalite", models.CharField(default="Guinéenne", max_length=50)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("adresse", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="professeurs/"),
                ),
                ("matricule", models.CharField(blank=True, max_length=20, unique=True)),
                ("specialite", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=100)),
                ("departement", models.CharField(max_length=100)),
                ("date_recrutement", models.DateField()),
            ],
            options={
                "verbose_name": "Professeur",
                "verbose_name_plural": "Professeurs",
                "ordering": ["nom"],
            },
        ),
    ]
