# Generated by Django 6.0.5 on 2026-05-14 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("credits", models.IntegerField(default=3)),
                (
                    "coefficient",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                ("filiere", models.CharField(max_length=100)),
                ("niveau", models.CharField(max_length=20)),
                ("annee_academique", models.CharField(max_length=9)),
                (
                    "semestre",
                    models.CharField(
                        choices=[("S1", "Semestre 1"), ("S2", "Semestre 2")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cours",
                "verbose_name_plural": "Cours",
            },
        ),
        migrations.CreateModel(
            name="Deliberation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee_academique", models.CharField(max_length=9)),
                (
                    "moyenne_generale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("admis", "Admis"),
                            ("ajourne", "Ajourné"),
                            ("autorise_dettes", "Autorisé avec dettes"),
                            ("redoublement", "Redoublement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("date_deliberation", models.DateTimeField(auto_now_add=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliberations",
                        to="inscriptions.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Délibération",
                "verbose_name_plural": "Délibérations",
                "unique_together": {("etudiant", "annee_academique")},
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_cc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "note_examen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "note_finale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("annee_academique", models.CharField(max_length=9)),
                ("date_saisie", models.DateTimeField(auto_now_add=True)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="academique.cours",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="inscriptions.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "unique_together": {("etudiant", "cours", "annee_academique")},
            },
        ),
    ]
