# Generated by Django 6.0.5 on 2026-07-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=20)),
                ("specialite", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=100)),
                ("departement", models.CharField(max_length=100)),
            ],
        ),
    ]
