# Generated by Django 6.0.5 on 2026-07-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0002_professeur"),
        ("cours", "0002_cours_etudiants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="cours",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="cours.cours",
            ),
        ),
        migrations.DeleteModel(
            name="Cours",
        ),
    ]
