# Generated by Django 6.0.5 on 2026-07-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0003_alter_note_cours_delete_cours"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliberation",
            name="validee",
            field=models.BooleanField(default=False),
        ),
    ]
