# Generated by Django 6.0.5 on 2026-07-09 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0004_deliberation_validee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliberation",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="deliberation",
            unique_together=set(),
        ),
    ]
