# Generated by Django 6.0.5 on 2026-07-09 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0005_alter_deliberation_options_and_more"),
        ("jury", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliberation",
            name="date_validation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliberation",
            name="jury_validateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jury.jury",
            ),
        ),
    ]
